name = "CartesianFrontTracking"
uuid = "6c5555df-b5b5-407d-917e-d56d7eaa128a"
authors = ["Fastaxx <Fastaxx@github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
